ALTER TABLE inventory_items ALTER COLUMN quantity TYPE DOUBLE PRECISION USING quantity::DOUBLE PRECISION;
ALTER TABLE inventory_items ALTER COLUMN min_quantity TYPE DOUBLE PRECISION USING min_quantity::DOUBLE PRECISION;
ALTER TABLE inventory_items ALTER COLUMN cost_per_unit TYPE DOUBLE PRECISION USING cost_per_unit::DOUBLE PRECISION;
ALTER TABLE inventory_transactions ALTER COLUMN quantity TYPE DOUBLE PRECISION USING quantity::DOUBLE PRECISION;
